#!/bin/bash

# Copyright (c) 2021 The NAVER Whale OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

SCRIPT_ROOT="$(dirname "$(readlink -f "$0")")"
SRC_ROOT="${SCRIPT_ROOT}/../../.."

APPLY_CMD=( "git am" )

PATCHES_TO_REPO=(
  "0001-Try-to-skip-grub-menu.patch,third_party/chromiumos-overlay"
)

for patch_to_repo in "${PATCHES_TO_REPO[@]}"; do
  IFS=","
  set -- $patch_to_repo
  PATCH=$1
  REPO=$2
  
  echo "Changing directory to ${SRC_ROOT}/${REPO}"
  cd "${SRC_ROOT}/${REPO}"

  echo "Applying ${SCRIPT_ROOT}/../patches/${PATCH}"
  git am "${SCRIPT_ROOT}/../patches/${PATCH}"
done

