#!/bin/bash

# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

readonly GPIO=345
readonly GPIO_PATH="/sys/class/gpio/gpio${GPIO}/"

log() {
  logger "[modem]" "$@"
}

has_modem() {
  cros_config /modem firmware-variant > /dev/null
}

is_modem_alive() {
  lsusb -d 2cb7: > /dev/null
}

has_modem || exit 0

log "stop modemmanager"
stop modemmanager

if [[ ! -d ${GPIO_PATH} ]]; then
  log "export GPIO ${GPIO}"
  echo ${GPIO} > /sys/class/gpio/export
  echo out > "${GPIO_PATH}/direction"
fi

log "assert GPIO ${GPIO}"
echo 0 > "${GPIO_PATH}/value"

# Now wait up to 30 seconds to ensure OS sees the modem disconnecting.
for i in {1..300}; do
  if ! is_modem_alive; then
    log "shutdown succeeded."
    break
  fi
  log "[attempt ${i}] modem is still on, wait for another 100ms..."
  sleep 0.1
done
